NH-68870: use multi-step commands to make lambda layer version public and removes `sam` usage

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,6 @@ orbs:
   aws-util: solarwindscloud/aws@0
   win: circleci/windows@5.0
   aws-cli: circleci/aws-cli@4.1.2
-  sam: circleci/aws-sam-serverless@5.0
   ghas: solarwinds-cloud/ghas@0.1.1
 
 envs: &default-envs
@@ -107,7 +106,6 @@ jobs:
       - checkout
       - aws-cli/setup:
           role_arn: ${AWS_LAMBDA_ROLE}
-      - sam/install
       - run:
           name: Build agent
           command: ./gradlew clean build -x test
@@ -144,17 +142,52 @@ jobs:
             VERSION=$(echo "$AGENTVERSION" | sed 's/[.]/_/g')
             LAYER_NAME="solarwinds-apm-java-$VERSION"
             touch arns.txt
+            layer_size=$(stat --printf=%s agent/build/lambda-layer/layer.zip)
             
+            set +e
             for region in "${regions[@]}"; do
-              sam deploy --resolve-s3 \
-                  --stack-name "solarwinds-java-lambda-layer-stack" \
-                  --region "$region" \
-                  --capabilities CAPABILITY_NAMED_IAM \
-                  --parameter-overrides LayerName="$LAYER_NAME" \
-                  --template agent/lambda/sam-template.yml
+              status=0
+              aws lambda publish-layer-version \
+                          --layer-name $LAYER_NAME \
+                          --compatible-runtimes "java17" "java11" "java8.al2" "java8" \
+                          --compatible-architectures "x86_64" "arm64" \
+                          --description "Solarwinds' apm java lambda instrumentation layer, version: $AGENTVERSION" \
+                          --region "$region" \
+                          --zip-file fileb://agent/build/lambda-layer/layer.zip \
+                          --output json > output.json
             
-              arn=$(aws lambda list-layer-versions --layer-name "$LAYER_NAME" --region "$region" --query 'max_by(LayerVersions, &Version).LayerVersionArn')
-              echo "${arn//\"/}"  >> arns.txt
+              status=$?
+              if [ "$status" != 0 ]; then
+                echo "FAILED: publish $region"
+                continue
+              fi
+            
+              pub_versionarn=$(jq -r '.LayerVersionArn' output.json)
+              pub_arn=$(jq -r '.LayerArn' output.json)
+              pub_version=$(jq -r '.Version' output.json)
+              pub_size=$(jq -r '.Content.CodeSize' output.json)
+            
+              echo '-- verifying published layer --'
+              if [ "$pub_size" != "$layer_size" ]; then
+                echo "FAILED: Region = $region, versonArn = $pub_versionarn published size = $pub_size, expected size = $layer_size"
+                continue
+              fi
+            
+              aws lambda add-layer-version-permission \
+                --region "$region" \
+                --layer-name "$pub_arn" \
+                --version-number "$pub_version" \
+                --principal '*' \
+                --action lambda:GetLayerVersion \
+                --statement-id global-GetLayerVersion
+            
+              status=$?
+              if [ "$status" != 0 ]; then
+                echo "FAILED: add permission region = $region, versionArn = $pub_versionarn"
+                continue
+              fi
+            
+              echo "$pub_versionarn" >> arns.txt
             done
       - store_artifacts:
           path: arns.txt
